services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - DATABASE_NAME=sweet_bananza
      - SERVER_PORT=3000
      - RUST_LOG=debug
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: